// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dialufvxlnianmoqhogx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRpYWx1ZnZ4bG5pYW5tb3Fob2d4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE1NjI0MTAsImV4cCI6MjA2NzEzODQxMH0.e4uRc95J3eAAHq42ZSXnQAPJX1RMFUcXAisjbmyevCk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});